- name: "get package facts"
  package_facts:

- name: "is apache2 or docker installed?"
  set_fact:
    apache2_installed: "{{ 'apache2' in ansible_facts.packages }}"
    docker_installed: "{{ 'docker-ce' in ansible_facts.packages}}"

- name: "stop apache daemon"
  when: apache2_installed
  service:
    name: apache2
    state: stopped
  register: apache2_stopped

- name: "is perun_apache container running?"
  when: docker_installed
  docker_container_info:
    name: perun_apache
  register: docker_perun_apache_container

- name: "stop perun_apache container"
  when: docker_installed and docker_perun_apache_container.exists and docker_perun_apache_container.container.State.Running
  docker_container:
    name: perun_apache
    state: stopped
  register: docker_perun_apache_stopped

- name: "get cert from certbot"
  command: >-
    certbot certonly --standalone
    --domain {{ certbot_hostname }}
    {% for i in certbot_alt_hostnames %}
      --domain {{ i }}
    {% endfor %}
    --cert-name {{ certbot_certname }}
    --non-interactive
    --quiet
    --agree-tos
    {{ certbot_account_options }}

- name: "restart apache if it was running originally"
  service:
    name: apache2
    state: started
  when: apache2_stopped.changed

- name: "restart perun_apache container if it was running originally"
  when: docker_installed and docker_perun_apache_container.exists and docker_perun_apache_stopped.changed
  docker_container:
    name: perun_apache
    state: started
