- name: "get package facts"
  package_facts:

- name: "is apache2 installed?"
  set_fact:
    apache2_installed: "{{ 'apache2' in ansible_facts.packages }}"

- name: "ensure apache is not running"
  service:
    name: apache2
    state: stopped
  when: apache2_installed
  register: apache2_stopped

- name: "get cert for {{ certbot_hostname }}"
  command: >-
    certbot certonly --standalone
    --domain {{ certbot_hostname }}
    {% for i in certbot_alt_hostnames %}
      --domain {{ i }}
    {% endfor %}
    --cert-name {{ certbot_certname }}
    --non-interactive
    --quiet
    --agree-tos
    {{ certbot_account_options }}
  args:
    creates: "/etc/letsencrypt/live/{{ certbot_certname }}/cert.pem"

- name: "restart apache if it was running originally"
  service:
    name: apache2
    state: started
  when: apache2_stopped.changed
