- name: "install certbot"
  apt:
    name:
      - ssl-cert
      - certbot
    state: present

- name: "get cert for {{ certbot_hostname }}"
  shell: >-
    certbot certonly --standalone --domain {{ certbot_hostname }}
    --non-interactive --quiet --agree-tos {{ certbot_account_options }}
